# Generated by Django 5.2 on 2025-04-29 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=120)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('remote_path', models.CharField(max_length=256)),
                ('server_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('destination_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_schedules', to='backup_app.serverconfig')),
                ('source_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedules', to='backup_app.serverconfig')),
            ],
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_created_at', models.DateTimeField(blank=True, null=True)),
                ('file_modified_at', models.DateTimeField(blank=True, null=True)),
                ('source_path', models.CharField(max_length=512)),
                ('destination_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_files', to=settings.AUTH_USER_MODEL)),
                ('destination_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_files', to='backup_app.serverconfig')),
                ('source_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='backup_app.serverconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('backup_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backup_app.backupfile')),
            ],
        ),
    ]
