# Generated by Django 5.2 on 2025-05-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfile',
            name='files_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backupfile',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
    ]
