# Generated by Django 5.2 on 2025-05-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_app', '0002_backupfile_files_count_backupfile_is_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupfile',
            name='files_count',
        ),
    ]
