# Generated by Django 5.2 on 2025-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_app', '0003_remove_backupfile_files_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfile',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
    ]
